// <auto-generated />
using System;
using Catalog.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.DAL.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251202164248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.DAL.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("b3e7c2e7-6b7b-4b7b-9b7b-7b7b7b7b7b7b"),
                            Name = "Phones"
                        },
                        new
                        {
                            CategoryId = new Guid("b3e7c2e7-6b7b-4b7b-9b7b-7b7b7b7b7b7c"),
                            Name = "Laptops"
                        },
                        new
                        {
                            CategoryId = new Guid("b3e7c2e7-6b7b-4b7b-9b7b-7b7b7b7b7b7d"),
                            Name = "Tablets"
                        },
                        new
                        {
                            CategoryId = new Guid("b3e7c2e7-6b7b-4b7b-9b7b-7b7b7b7b7b7e"),
                            Name = "Monitors"
                        },
                        new
                        {
                            CategoryId = new Guid("b3e7c2e7-6b7b-4b7b-9b7b-7b7b7b7b7b7f"),
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("Catalog.DAL.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_quantity");

                    b.HasKey("ProductId")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_sku");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_price_greater_than_zero", "price > 0");

                            t.HasCheckConstraint("ck_stock_quantity_greater_than_zero", "stock_quantity > 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("b3e7c2e7-6b7b-4b7b-9b7b-7b7b7b7b7b7b"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "iPhone X",
                            Price = 21000m,
                            RowVersion = 0u,
                            Sku = "iphonex",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("b3e7c2e7-6b7b-4b7b-9b7b-7b7b7b7b7b7c"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "MacBook Pro 13",
                            Price = 50000m,
                            RowVersion = 0u,
                            Sku = "macbookpro13",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("b3e7c2e7-6b7b-4b7b-9b7b-7b7b7b7b7b7d"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "iPad Pro 11",
                            Price = 30000m,
                            RowVersion = 0u,
                            Sku = "ipadpro11",
                            StockQuantity = 5
                        });
                });

            modelBuilder.Entity("Catalog.DAL.Models.ProductDetails", b =>
                {
                    b.Property<Guid>("DetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("details_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<float>("Weight_Kg")
                        .HasColumnType("real")
                        .HasColumnName("weight_kg");

                    b.HasKey("DetailsId")
                        .HasName("pk_product_details");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_details_product_id");

                    b.ToTable("product_details", null, t =>
                        {
                            t.HasCheckConstraint("ck_weight_kg_greater_than_zero", "weight_kg > 0");
                        });
                });

            modelBuilder.Entity("Catalog.DAL.Models.ProductTag", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("ProductId", "TagId")
                        .HasName("pk_product_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_product_tags_tag_id");

                    b.ToTable("product_tags", (string)null);
                });

            modelBuilder.Entity("Catalog.DAL.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("TagId")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Catalog.DAL.Models.Product", b =>
                {
                    b.HasOne("Catalog.DAL.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Catalog.DAL.Models.ProductDetails", b =>
                {
                    b.HasOne("Catalog.DAL.Models.Product", "Product")
                        .WithOne("ProductDetails")
                        .HasForeignKey("Catalog.DAL.Models.ProductDetails", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_details_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Catalog.DAL.Models.ProductTag", b =>
                {
                    b.HasOne("Catalog.DAL.Models.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_tags_products_product_id");

                    b.HasOne("Catalog.DAL.Models.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_tags_tags_tag_id");

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Catalog.DAL.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Catalog.DAL.Models.Product", b =>
                {
                    b.Navigation("ProductDetails")
                        .IsRequired();

                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("Catalog.DAL.Models.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
